service: thumbnail-serverless

frameworkVersion: '2'

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []
  bucketTarget: plando-attachments-local-development-bucket-v2
  bucketThumbnail: plando-thumbnails-development-bucket
  
provider:
  name: aws
  runtime: python3.7
  region: eu-central-1
  environment:
    BUCKET_THUMBNAIL: "${self:custom.bucketThumbnail}"
    BUCKET_TARGET: "${self:custom.bucketTarget}"
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::${self:custom.bucketThumbnail}/*"

plugins:
  - serverless-python-requirements
  
functions:
  create_thumbnail:
    handler: create_thumbnail.handler
    events:
      - s3:
          bucket: "${self:custom.bucketTarget}"
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
          existing: true
      - s3:
          bucket: "${self:custom.bucketTarget}"
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
          existing: true