service: thumbnail-serverless

frameworkVersion: '2'

custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy: []
  bucketThumbnail: thumbnail-serverless-dev-serverlessdeploymentbuck-5u1h26ig44jp
  


provider:
  name: aws
  runtime: python3.7
  environment:
    BUCKET_NAME: "${self:custom.bucketThumbnail}"
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:PutObject"
        - "s3:PutObjectAcl"
      Resource: "arn:aws:s3:::${self:custom.bucketThumbnail}/*"

plugins:
  - serverless-python-requirements
  
functions:
  create_thumbnail:
    handler: create_thumbnail.handler
    events:
      - s3:
          bucket: "${self:custom.bucketThumbnail}"
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
            - suffix: .jpg
          existing: true
      - s3:
          bucket: "${self:custom.bucketThumbnail}"
          event: s3:ObjectCreated:*
          rules:
            - prefix: originals/
            - suffix: .png
          existing: true